# https://help.github.com/en/articles/workflow-syntax-for-github-actions#about-yaml-syntax-for-workflows
name: CI

on: [push]

jobs:
    needs: job1
  build-macOS-latest-msbuild:
    runs-on: macOS-latest    
    steps:
    - uses: actions/checkout@v1
    - name: build-macOS-latest-msbuild
      run: build-macOS-latest-msbuild
    - name: build-macOS-latest-msbuild
      run: |
        msbuild /restore ./source/*.sln

  test-build-macOS-latest-msbuild:
    runs-on: macOS-latest    
    needs: build-macOS-latest-msbuild
    steps:
    - uses: actions/checkout@v1
    - name: test-build-macOS-latest-msbuild
      run: test-build-macOS-latest-msbuild
    - name: test-build-macOS-latest-msbuild
      run: |
        msbuild /restore ./tests/unit-tests/project-references/*.sln

  build-macOS-latest-dotnet:
    runs-on: macOS-latest    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        dotnet restore ./source/*.sln
        dotnet build ./source/*.sln

  build-windows-latest:  
    runs-on: windows-latest    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        set MSBUILD="C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe"
        %msbuild% /restore ./source/Source.sln

  build-ubuntu-latest:  
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        msbuild /restore ./source/Source.sln

